/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface DreamJournalInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createDream"
      | "getDreamContentByte"
      | "getDreamContentLength"
      | "getDreamCount"
      | "getDreamIds"
      | "getDreamMeta"
      | "protocolId"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "DreamCreated"): EventFragment;

  encodeFunctionData(
    functionFragment: "createDream",
    values: [string, BytesLike[], BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDreamContentByte",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDreamContentLength",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDreamCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDreamIds",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDreamMeta",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "createDream",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDreamContentByte",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDreamContentLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDreamCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDreamIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDreamMeta",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
}

export namespace DreamCreatedEvent {
  export type InputTuple = [
    id: BigNumberish,
    owner: AddressLike,
    title: string,
    createdAt: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    owner: string,
    title: string,
    createdAt: bigint
  ];
  export interface OutputObject {
    id: bigint;
    owner: string;
    title: string;
    createdAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DreamJournal extends BaseContract {
  connect(runner?: ContractRunner | null): DreamJournal;
  waitForDeployment(): Promise<this>;

  interface: DreamJournalInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createDream: TypedContractMethod<
    [title: string, encContent: BytesLike[], inputProof: BytesLike],
    [bigint],
    "nonpayable"
  >;

  getDreamContentByte: TypedContractMethod<
    [id: BigNumberish, index: BigNumberish],
    [string],
    "view"
  >;

  getDreamContentLength: TypedContractMethod<
    [id: BigNumberish],
    [bigint],
    "view"
  >;

  getDreamCount: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  getDreamIds: TypedContractMethod<[user: AddressLike], [bigint[]], "view">;

  getDreamMeta: TypedContractMethod<
    [id: BigNumberish],
    [
      [string, string, bigint] & {
        owner: string;
        title: string;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createDream"
  ): TypedContractMethod<
    [title: string, encContent: BytesLike[], inputProof: BytesLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getDreamContentByte"
  ): TypedContractMethod<
    [id: BigNumberish, index: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDreamContentLength"
  ): TypedContractMethod<[id: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDreamCount"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDreamIds"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getDreamMeta"
  ): TypedContractMethod<
    [id: BigNumberish],
    [
      [string, string, bigint] & {
        owner: string;
        title: string;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "DreamCreated"
  ): TypedContractEvent<
    DreamCreatedEvent.InputTuple,
    DreamCreatedEvent.OutputTuple,
    DreamCreatedEvent.OutputObject
  >;

  filters: {
    "DreamCreated(uint256,address,string,uint64)": TypedContractEvent<
      DreamCreatedEvent.InputTuple,
      DreamCreatedEvent.OutputTuple,
      DreamCreatedEvent.OutputObject
    >;
    DreamCreated: TypedContractEvent<
      DreamCreatedEvent.InputTuple,
      DreamCreatedEvent.OutputTuple,
      DreamCreatedEvent.OutputObject
    >;
  };
}
